# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reverse_service/reverse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/reverse_service/reverse.proto',
  package='reverse',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#proto/reverse_service/reverse.proto\x12\x07reverse\"\'\n\rRequestString\x12\x16\n\x0erequest_string\x18\x01 \x01(\t\"B\n\x0eResponseString\x12\x17\n\x0foriginal_string\x18\x01 \x01(\t\x12\x17\n\x0freversed_string\x18\x02 \x01(\t2H\n\x08Reverser\x12<\n\x07Reverse\x12\x16.reverse.RequestString\x1a\x17.reverse.ResponseString\"\x00\x62\x06proto3')
)




_REQUESTSTRING = _descriptor.Descriptor(
  name='RequestString',
  full_name='reverse.RequestString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_string', full_name='reverse.RequestString.request_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=87,
)


_RESPONSESTRING = _descriptor.Descriptor(
  name='ResponseString',
  full_name='reverse.ResponseString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_string', full_name='reverse.ResponseString.original_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reversed_string', full_name='reverse.ResponseString.reversed_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['RequestString'] = _REQUESTSTRING
DESCRIPTOR.message_types_by_name['ResponseString'] = _RESPONSESTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestString = _reflection.GeneratedProtocolMessageType('RequestString', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTRING,
  '__module__' : 'proto.reverse_service.reverse_pb2'
  # @@protoc_insertion_point(class_scope:reverse.RequestString)
  })
_sym_db.RegisterMessage(RequestString)

ResponseString = _reflection.GeneratedProtocolMessageType('ResponseString', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTRING,
  '__module__' : 'proto.reverse_service.reverse_pb2'
  # @@protoc_insertion_point(class_scope:reverse.ResponseString)
  })
_sym_db.RegisterMessage(ResponseString)



_REVERSER = _descriptor.ServiceDescriptor(
  name='Reverser',
  full_name='reverse.Reverser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=157,
  serialized_end=229,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reverse',
    full_name='reverse.Reverser.Reverse',
    index=0,
    containing_service=None,
    input_type=_REQUESTSTRING,
    output_type=_RESPONSESTRING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REVERSER)

DESCRIPTOR.services_by_name['Reverser'] = _REVERSER

# @@protoc_insertion_point(module_scope)
